"use strict";
const api_request = require("../../api/request.js");
const CS = { role: "cs" };
const getCsProfile = () => api_request.get("/cs/profile", {}, CS);
const updateCsProfile = (data) => api_request.put("/cs/profile", data, CS);
const getDashboard = () => api_request.get("/cs/dashboard", {}, CS);
const getCsOrderList = (params) => api_request.get("/cs/order/list", params, CS);
const getCsOrderDetail = (id) => api_request.get(`/cs/order/${id}`, {}, CS);
const getCsOrderProgress = (id) => api_request.get(`/cs/order/${id}/progress`, {}, CS);
const assignOrder = (orderId, playerId) => api_request.post(`/cs/order/${orderId}/assign/${playerId}`, {}, CS);
const csRefundOrder = (orderId) => api_request.post(`/cs/order/${orderId}/refund`, {}, CS);
const csConfirmOrder = (orderId) => api_request.post(`/cs/order/${orderId}/confirm`, {}, CS);
const getCsComplaintList = (params) => api_request.get("/cs/complaint/list", params, CS);
const processCsComplaint = (id, data) => api_request.put(`/cs/complaint/${id}/process`, data, CS);
const resolveCsComplaint = (id, data) => api_request.put(`/cs/complaint/${id}/resolve`, data, CS);
const getCsUserList = (params) => api_request.get("/cs/user/list", params, CS);
const updateCsUserStatus = (id, data) => api_request.put(`/cs/user/${id}/status`, data, CS);
const getCsPlayerList = (params) => api_request.get("/cs/player/list", params, CS);
const getCsPlayerAssignList = (params) => api_request.get("/cs/player/assign-list", params, CS);
const auditCsPlayer = (id, data) => api_request.put(`/cs/player/${id}/audit`, data, CS);
const freezeCsPlayer = (id, data = {}) => api_request.put(`/cs/player/${id}/freeze`, data, CS);
const getCsWithdrawList = (params) => api_request.get("/cs/withdraw/list", params, CS);
const approveCsWithdraw = (id) => api_request.put(`/cs/withdraw/${id}/approve`, {}, CS);
const rejectCsWithdraw = (id, data) => api_request.put(`/cs/withdraw/${id}/reject`, data, CS);
const getCsProductList = (params) => api_request.get("/cs/product/list", params, CS);
const saveCsProduct = (data) => api_request.post("/cs/product", data, CS);
const getCsCategoryList = (params) => api_request.get("/cs/category/list", params, CS);
const saveCsCategory = (data) => api_request.post("/cs/category", data, CS);
const getCsChatSessions = (params) => api_request.get("/cs/chat/sessions", params, CS);
const getCsChatMessages = (params) => api_request.get("/common/chat/message/list", params, CS);
const csChatMarkRead = (sessionId) => api_request.post(`/common/chat/message/read?sessionId=${sessionId}`, {}, CS);
const getCsComplaintDetail = (id) => api_request.get(`/cs/complaint/${id}`, {}, CS);
const getCsPlayerDetail = (id) => api_request.get(`/cs/player/${id}`, {}, CS);
const getCsWithdrawDetail = (id) => api_request.get(`/cs/withdraw/${id}`, {}, CS);
const getCsProductDetail = (id) => api_request.get(`/cs/product/${id}`, {}, CS);
const deleteCsCategory = (id) => api_request.del(`/cs/category/${id}`, {}, CS);
const getQuickReplyList = (params) => api_request.get("/system/quick-reply/list", params, CS);
const getActiveQuickReplies = (params) => api_request.get("/system/quick-reply/active", params, CS);
const addQuickReply = (data) => api_request.post("/system/quick-reply", data, CS);
const updateQuickReply = (data) => api_request.put("/system/quick-reply", data, CS);
const deleteQuickReply = (id) => api_request.del(`/system/quick-reply/${id}`, {}, CS);
const getCsRelayList = (params) => api_request.get("/cs/relay/list", params, CS);
const approveCsRelay = (id, data) => api_request.post(`/cs/relay/${id}/approve`, data, CS);
const rejectCsRelay = (id, data) => api_request.post(`/cs/relay/${id}/reject`, data, CS);
const getCsReplaceList = (params) => api_request.get("/cs/replace/list", params, CS);
const approveCsReplace = (id, data) => api_request.put(`/cs/replace/${id}/approve`, data, CS);
const rejectCsReplace = (id, data) => api_request.put(`/cs/replace/${id}/reject`, data, CS);
exports.addQuickReply = addQuickReply;
exports.approveCsRelay = approveCsRelay;
exports.approveCsReplace = approveCsReplace;
exports.approveCsWithdraw = approveCsWithdraw;
exports.assignOrder = assignOrder;
exports.auditCsPlayer = auditCsPlayer;
exports.csChatMarkRead = csChatMarkRead;
exports.csConfirmOrder = csConfirmOrder;
exports.csRefundOrder = csRefundOrder;
exports.deleteCsCategory = deleteCsCategory;
exports.deleteQuickReply = deleteQuickReply;
exports.freezeCsPlayer = freezeCsPlayer;
exports.getActiveQuickReplies = getActiveQuickReplies;
exports.getCsCategoryList = getCsCategoryList;
exports.getCsChatMessages = getCsChatMessages;
exports.getCsChatSessions = getCsChatSessions;
exports.getCsComplaintDetail = getCsComplaintDetail;
exports.getCsComplaintList = getCsComplaintList;
exports.getCsOrderDetail = getCsOrderDetail;
exports.getCsOrderList = getCsOrderList;
exports.getCsOrderProgress = getCsOrderProgress;
exports.getCsPlayerAssignList = getCsPlayerAssignList;
exports.getCsPlayerDetail = getCsPlayerDetail;
exports.getCsPlayerList = getCsPlayerList;
exports.getCsProductDetail = getCsProductDetail;
exports.getCsProductList = getCsProductList;
exports.getCsProfile = getCsProfile;
exports.getCsRelayList = getCsRelayList;
exports.getCsReplaceList = getCsReplaceList;
exports.getCsUserList = getCsUserList;
exports.getCsWithdrawDetail = getCsWithdrawDetail;
exports.getCsWithdrawList = getCsWithdrawList;
exports.getDashboard = getDashboard;
exports.getQuickReplyList = getQuickReplyList;
exports.processCsComplaint = processCsComplaint;
exports.rejectCsRelay = rejectCsRelay;
exports.rejectCsReplace = rejectCsReplace;
exports.rejectCsWithdraw = rejectCsWithdraw;
exports.resolveCsComplaint = resolveCsComplaint;
exports.saveCsCategory = saveCsCategory;
exports.saveCsProduct = saveCsProduct;
exports.updateCsProfile = updateCsProfile;
exports.updateCsUserStatus = updateCsUserStatus;
exports.updateQuickReply = updateQuickReply;
//# sourceMappingURL=../../../.sourcemap/mp-weixin/pages-cs/api/cs.js.map
