"use strict";
const api_request = require("./request.js");
const getPlayerProfile = (opts = {}) => api_request.get("/player/profile", {}, { role: opts.role || "player", ...opts });
const toggleOnlineStatus = (online) => api_request.post(`/player/online-status?online=${online}`, {}, { role: "player" });
const applyPlayer = (data) => api_request.post("/player/apply", data);
const getPlayerHome = () => api_request.get("/player/home", {}, { role: "player" });
const getPlayerRemind = (opts = {}) => api_request.get("/player/remind", {}, { role: "player", ...opts });
const getOrderHall = (params) => api_request.get("/player/order/hall", params, { role: "player" });
const acceptOrder = (id) => api_request.post(`/player/order/${id}/accept`, {}, { role: "player" });
const startOrder = (id) => api_request.post(`/player/order/${id}/start`, {}, { role: "player" });
const completeOrder = (id, data = {}) => api_request.post(`/player/order/${id}/complete`, data, { role: "player" });
const getPlayerOrderProgress = (id) => api_request.get(`/player/order/${id}/progress`, {}, { role: "player" });
const rejectAssign = (id) => api_request.post(`/player/order/${id}/reject-assign`, {}, { role: "player" });
const inviteTeammate = (id, data) => api_request.post(`/player/order/${id}/invite-teammate`, data, { role: "player" });
const acceptInvite = (id) => api_request.post(`/player/order/${id}/accept-invite`, {}, { role: "player" });
const rejectInvite = (id) => api_request.post(`/player/order/${id}/reject-invite`, {}, { role: "player" });
const getInviteList = (params) => api_request.get("/player/order/invite-list", params, { role: "player" });
const getAvailableTeammates = (params) => api_request.get("/player/order/teammate/available", params, { role: "player" });
const getMyWork = (params) => api_request.get("/player/work/my", params, { role: "player" });
const submitWorkProgress = (orderId, data) => api_request.post(`/player/order/${orderId}/progress`, data, { role: "player" });
const getEarningsSummary = () => api_request.get("/player/earnings/summary", {}, { role: "player" });
const getEarningsDetail = (params) => api_request.get("/player/earnings/detail", params, { role: "player" });
const applyWithdraw = (data) => api_request.post("/player/withdraw", data, { role: "player" });
const getWithdrawList = (params) => api_request.get("/player/withdraw", params, { role: "player" });
const getWithdrawDetail = (id) => api_request.get(`/player/withdraw/${id}`, {}, { role: "player" });
const getAccountList = () => api_request.get("/player/account", {}, { role: "player" });
const addAccount = (data) => api_request.post("/player/account", data, { role: "player" });
const updateAccount = (data) => api_request.put("/player/account", data, { role: "player" });
const deleteAccount = (id) => api_request.del(`/player/account/${id}`, {}, { role: "player" });
const replaceSelf = (orderId) => api_request.post(`/player/order/${orderId}/replace-self`, {}, { role: "player" });
const replaceAll = (orderId) => api_request.post(`/player/order/${orderId}/replace-all`, {}, { role: "player" });
const replaceTeammate = (orderId) => api_request.post(`/player/order/${orderId}/replace-teammate`, {}, { role: "player" });
exports.acceptInvite = acceptInvite;
exports.acceptOrder = acceptOrder;
exports.addAccount = addAccount;
exports.applyPlayer = applyPlayer;
exports.applyWithdraw = applyWithdraw;
exports.completeOrder = completeOrder;
exports.deleteAccount = deleteAccount;
exports.getAccountList = getAccountList;
exports.getAvailableTeammates = getAvailableTeammates;
exports.getEarningsDetail = getEarningsDetail;
exports.getEarningsSummary = getEarningsSummary;
exports.getInviteList = getInviteList;
exports.getMyWork = getMyWork;
exports.getOrderHall = getOrderHall;
exports.getPlayerHome = getPlayerHome;
exports.getPlayerOrderProgress = getPlayerOrderProgress;
exports.getPlayerProfile = getPlayerProfile;
exports.getPlayerRemind = getPlayerRemind;
exports.getWithdrawDetail = getWithdrawDetail;
exports.getWithdrawList = getWithdrawList;
exports.inviteTeammate = inviteTeammate;
exports.rejectAssign = rejectAssign;
exports.rejectInvite = rejectInvite;
exports.replaceAll = replaceAll;
exports.replaceSelf = replaceSelf;
exports.replaceTeammate = replaceTeammate;
exports.startOrder = startOrder;
exports.submitWorkProgress = submitWorkProgress;
exports.toggleOnlineStatus = toggleOnlineStatus;
exports.updateAccount = updateAccount;
//# sourceMappingURL=../../.sourcemap/mp-weixin/api/player.js.map
